services:
  server:
    build:
      context: .
      target: final
    environment:
      MONGODB_URI: mongodb://db:27017
      MONGODB_DATABASE: life_compass
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mongo:8.0
    volumes:
      - life-compass-data:/data/db
    ports:
      - '27017:27017'

volumes:
  life-compass-data:
